### ISSUE TITLE
thrift binary type converted into pyi string type

### ISSUE THREAD

**Issue by wdyin** [unmade/thrift-pyi#25]
I really appreciate this awesome tool and it helped me a lot. But I just figure out that if a type is `binary` in thrift, it will be converted into `str` in pyi, instead of `byte` . I wonder if this behavior is expected.

**Comment by unmade** [comment]
Hi, thanks for using it!

Can you please tell what thrift version you're using?

I do believe it is expected behaviour for thrifty (v1), but not for thriftpy2.
About a year ago I had this MR https://github.com/Thriftpy/thriftpy2/pull/139

**Comment by wdyin** [comment]
Yeah I'm using thriftpy2, so it's a little bit confusing when I see errors from pyright. Do you consider it reasonable to enable byte anno from binary? Actually thriftpy2 is used a lot.

**Comment by unmade** [comment]
I see.
I will take a look at this in the next couple days

**Comment by wdyin** [comment]
any follow-ups on this issue? thanks!

**Comment by unmade** [comment]
I'm sorry it took me so long

Prior thriftpy2 v0.4.13 BINARY and STRING are the same types. Since v0.4.13 BINARY is indeed a separate type and will be cast to `bytes` by `thrift-pyi`. 

So, my guess is that you should just update the thriftpy2 version to 0.4.13 or higher and you'll be fine

**Comment by matthewess** [comment]
We are using thriftpy v0.4.14 at work and still hitting this issue of binary types being inferred as `str`.

Example protocol:
```thrift
struct Message {
  1: binary body,
  2: binary key,
  3: optional i32 partition = -1,
  4: optional i64 timestamp_micros = -1
}
```

Generated type:
```python
@dataclass
class Message:
    body: Optional[str] = None
    key: Optional[str] = None
    partition: Optional[int] = -1
    timestamp_micros: Optional[int] = -1

```

**Comment by unmade** [comment]
@matthewess 

As far as I can see they reverted separate BINARY type: 
- https://github.com/Thriftpy/thriftpy2/pull/157
- https://github.com/Thriftpy/thriftpy2/issues/156

But right now it's back in the master branch, they just haven't made a release yet:
- https://github.com/Thriftpy/thriftpy2/pull/164

So for now we just have to wait for a new release, because there is no way to distinguish between `STRING` and `BINARY`

**Comment by unmade** [comment]
@JayH5 
I'll add binary support, but it can take me a week or so to find some time. The project is open for pull requests, so feel free to create one

**Comment by unmade** [comment]
I've added support for binary types
For `thriftpy2` versions that define `BINARY` as `STRING` alias the result value will be `str`, for newer version - `bytes`

Feel free to re-open in case of any problem
