### ISSUE TITLE
Empty exceptions generate invalid python

### ISSUE THREAD

**Issue by paulroub** [unmade/thrift-pyi#27]
In thrift, it's legal to declare exceptions with no members, e.g.

```thrift
exception Foo {}
```

thrift-pyi doesn't handle this well, leaving nothing where the fields would have gone. Without a nested `pass`, this leads to unparseable python:

```py
class Foo(Exception):

class SomeOtherClass(Exception):
    message: Optional[str] = "This one is OK"
```

**Comment by unmade** [comment]
I made new release with your fix. Please install version 0.2.1

Thanks for using `thrift-pyi` and contributing to the project.
