### ISSUE TITLE
Support for `const`s being mapped to constants in Python

### ISSUE THREAD

**Issue by FrankPortman** [unmade/thrift-pyi#42]
Thank you for making this package! I am wondering if it would be an easy lift to support `const`s in Thrift.

For example:

```
const map<int, int> A = {
  1: 1,
  2: 2,
  3: 3
}
```

generating something like

```
from typing import *

A: dict[int, int] = {
  1: 1,
  2: 2,
  3: 3
}
```

I would be willing to take a stab at a PR if you give me some pointers on where to look.

**Comment by unmade** [comment]
Hey @FrankPortman!

I'm afraid that won't be possible until thriftpy2 supports `const` directive. As of now I'm getting the following error when `const` is present in the stub file:

```
>>> import thriftpy2
>>> thriftpy2.load("/Users/unmade/src/unmade/thrift-pyi/example/interfaces/shared.thrift")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/unmade/src/unmade/thrift-pyi/.venv/lib/python3.9/site-packages/thriftpy2/parser/__init__.py", line 36, in load
    thrift = parse(path, module_name, include_dirs=include_dirs,
  File "/Users/unmade/src/unmade/thrift-pyi/.venv/lib/python3.9/site-packages/thriftpy2/parser/parser.py", line 600, in parse
    parser.parse(data)
  File "/Users/unmade/src/unmade/thrift-pyi/.venv/lib/python3.9/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/unmade/src/unmade/thrift-pyi/.venv/lib/python3.9/site-packages/ply/yacc.py", line 1120, in parseopt_notrack
    p.callable(pslice)
  File "/Users/unmade/src/unmade/thrift-pyi/.venv/lib/python3.9/site-packages/thriftpy2/parser/parser.py", line 111, in p_const
    val = _cast(p[2], p.lineno(3))(p[5])
  File "/Users/unmade/src/unmade/thrift-pyi/.venv/lib/python3.9/site-packages/thriftpy2/parser/parser.py", line 785, in __cast_map
    for key in v:
RuntimeError: dictionary changed size during iteration
```

**Comment by FrankPortman** [comment]
Thank you for the quick response 🙏.

Can you share what version of `thriftpy2` you're running and what you modified your `shared.thrift` file to have in it?

For both Python 3.9 and Python 3.10, with `thriftpy2==0.4.16` I get the following:

```thrift
// test.thrift 

namespace scala test.thriftscala
namespace py test.thriftpy

enum Foo {
    Baz,
    Bar
}

const map<i32, i32> FooMap = {
    0: 0,
    1: 1,
    2: 2
}
```

```python
In [1]: import thriftpy2

In [2]: thrift = thriftpy2.load("test.thrift")

In [3]: thrift.Foo.Bar
Out[3]: 1

In [4]: thrift.FooMap
Out[4]: {0: 0, 1: 1, 2: 2}
```

**Comment by unmade** [comment]
Oh, my bad, I didn't notice a typo (map<int, int>) in the original example and copy-pasted it as is. That's why it was failing. 

Since `thriftpy2` supports it, it shouldn't be very hard to support it in that library as well. I haven't touch a library for a while and I need to take a closer look at it to provides some guides on contributing. Maybe I try to implement it myself

**Comment by FrankPortman** [comment]
Thanks for looking into this! If you get part of something up and need help taking it to the finish line then I'm happy to jump in.

**Comment by unmade** [comment]
I've added support for `const`! Please check the `0.7.0` version

**Comment by FrankPortman** [comment]
Works great - thanks!
