### ISSUE TITLE
Imported/Included structs are referenced correctly in type annotation but not constructor call, for consts

### ISSUE THREAD

**Issue by FrankPortman** [unmade/thrift-pyi#50]
Foo1.thrift:

```
struct FooData {
    1: required string hey
    2: required string hi
}
```

Foo2.thrift:

```
include "Foo1.thrift"

const Foo1.FooData imported_const = {
    "hey": "hey",
    "hi": "hi"
}
```

Generated code Foo2.py:

```
from . import Foo1

imported_const: Foo1.FooData = FooData(hey="hey", hi="hi")
```

so the `Foo1.FooData` type annotation ends up being correct, but the constructor call is not valid code, since it has not been imported to be able to reference without `Foo1` namespace.

I can't immediately tell from the source code whether this is something that you might be able to control or if we are the mercy of `thriftpy2` here. If the latter, I'm wondering if you have any suggested workarounds :).

Thanks again for all the work you do in creating and maintaining this library. If you couldn't tell based on the opened issues and pull requests over this last year, me and @soaxelbrooke have been getting a lot of use out of this library!

**Comment by unmade** [comment]
Hey @FrankPortman 

Thanks for reporting the issue. I think we have two options here:
1. switch to wild-card imports (probably not a good choice, cause we there can be ambiguity with two constants with the same, but from different modules)
2. do a bit of resolving in correct type name similar to what I do with type annotations

I'll look into this during the week

**Comment by FrankPortman** [comment]
Hi, thanks for looking into this. Agreed with (2) being the preferred route. I actually started poking around a little bit myself to see if I can have `guess_type` or `get_python_type` do this. Happy to collaborate.

**Comment by unmade** [comment]
A small update on the issue: I hadn't been able to give it a look yet, but hopefully upcoming week promise to be less busy for me

**Comment by FrankPortman** [comment]
No worries - we appreciate any and all help on whatever timeline works for you.

**Comment by unmade** [comment]
> I'll look into this during the week

sorry, that turned out to be a big lie :) 
I was pretty busy the whole time, but hopefully I can get my hand on it in the upcoming weeks

**Comment by unmade** [comment]
Hey, it looks like I've found a nice workaround for the problem. Please checkout v1.2.0 and let me know in case any troubles
